# Generated by Django 2.1.7 on 2019-03-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrap', '0004_auto_20190319_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='date',
        ),
    ]
