# Generated by Django 2.1.7 on 2019-03-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrap', '0005_remove_text_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
