# Generated by Django 2.1.7 on 2019-03-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrap', '0006_text_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
